<?php

                
/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */

function event_meta_box_get_meta( $value ) {
	global $post;

	$field = get_post_meta( $post->ID, $value, true );
	if ( ! empty( $field ) ) {
		return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
	} else {
		return false;
	}
}

function event_meta_box_add_meta_box() {
	add_meta_box(
		'event_meta_box-event-meta-box',
		__( 'Event Meta Box', 'event_meta_box' ),
		'event_meta_box_html',
		array('lccc_event','lccc_announcement'),
		'advanced',
		'core'
	);
}
add_action( 'add_meta_boxes', 'event_meta_box_add_meta_box' );


function event_meta_box_html( $post) {
	wp_nonce_field( '_event_meta_box_nonce', 'event_meta_box_nonce' ); ?>
	
<script>
jQuery(document).ready(function(){
jQuery('#event_start_date').datepicker({
	dateFormat: "yy-mm-dd"
});
jQuery('#event_start_time').timepicker({
	timeFormat: "hh:mm tt"
});
jQuery('#event_end_date').datepicker({
	dateFormat: "yy-mm-dd"
});
jQuery('#event_end_time').timepicker({
	timeFormat: "hh:mm tt"
});	

});
</script>

<h4>Submitted by:</h4>
	<p>
		<label for="event_meta_box_name"><?php _e( 'Your Name', 'event_meta_box' ); ?></label><br>
		<input class="widefat" type="text" name="event_meta_box_name" id="event_meta_box_name" value="<?php echo event_meta_box_get_meta( 'event_meta_box_name' ); ?>">
	
	</p>	
<p>
		<label for="event_meta_box_e_mail"><?php _e( 'E-Mail', 'event_meta_box' ); ?></label><br>
		<input class="widefat"  type="text" name="event_meta_box_e_mail" id="event_meta_box_e_mail" value="<?php echo event_meta_box_get_meta( 'event_meta_box_e_mail' ); ?>">
	
	</p>
<p>
		<label for="event_meta_box_phone"><?php _e( 'Phone', 'event_meta_box' ); ?></label><br>
		<input class="widefat"  type="text" name="event_meta_box_phone" id="event_meta_box_phone" value="<?php echo event_meta_box_get_meta( 'event_meta_box_phone' ); ?>">
	
	</p>		
	<p>
		<label for="event_meta_box_department_organization_sponsor_"><?php _e( 'Sponsoring/Host Department or Organization:', 'event_meta_box' ); ?></label><br>
		<input class="widefat"  type="text" name="event_meta_box_department_organization_sponsor_" id="event_meta_box_department_organization_sponsor_" value="<?php echo event_meta_box_get_meta( 'event_meta_box_department_organization_sponsor_' ); ?>">
	</p>
<p>
<br>
	<p>
<h4 class="metabox-field-title">Audience:</h4>

	<p>
		<input type="checkbox" name="event_meta_box_employee" id="event_meta_box_employee" value="LCCC Employees" <?php echo ( event_meta_box_get_meta( 'event_meta_box_employee' ) === 'LCCC Employees' ) ? 'checked' : ''; ?>>
		<label for="event_meta_box_employee"><?php _e( 'LCCC Employees', 'lccc_event_metabox' ); ?></label>	
</p>	
<p>
		<input type="checkbox" name="event_meta_box_community" id="event_meta_box_community" value="Community and Perspective Students" <?php echo ( event_meta_box_get_meta( 'event_meta_box_community' ) === 'Community and Perspective Students' ) ? 'checked' : ''; ?>>
		<label for="event_meta_box_community"><?php _e( 'Community and Perspective Students', 'lccc_event_metabox' ); ?></label>	
</p>
		<p>
		<input type="checkbox" name="event_meta_box_students" id="event_meta_box_students" value="LCCC Students" <?php echo ( event_meta_box_get_meta( 'event_meta_box_students' ) === 'LCCC Students' ) ? 'checked' : ''; ?>>
		<label for="event_meta_box_students"><?php _e( 'LCCC Students', 'lccc_event_metabox' ); ?></label>	
</p>

<h4 class="metabox-field-title">Event Location</h4><br>
<select name='event_meta_box_event_location' id='event_meta_box_event_location'>
 		<?php 
			$mypages = get_pages('post_type=lccc_location');
			foreach($mypages as $page)
			{
				?><option><?php echo $page->post_title;?></option><?php
			}
			?>
</select>
<h4 class="metabox-field-title">Ticket Price(s):</h4>
<p>
		<input type="text" name="event_meta_box_ticket_price_s_" id="event_meta_box_ticket_price_s_" value="<?php echo event_meta_box_get_meta( 'event_meta_box_ticket_price_s_' ); ?>">
	</p>
<h4 class="metabox-field-title">Event Dates and Times:</h4>

<p>		
		<label for="event_start_date"><?php _e( 'Event Start date:', 'event_meta_box' ); ?></label><br>
		<input type="text" name="event_start_date" id="event_start_date" value="<?php echo event_meta_box_get_meta( 'event_start_date' ); ?>">
	</p>

<p>		
		<label for="event_start_time"><?php _e( 'Event Start time:', 'event_meta_box' ); ?></label><br>
		<input type="text" name="event_start_time" id="event_start_time" value="<?php echo event_meta_box_get_meta( 'event_start_time' ); ?>">
	</p>

<p>
		<label for="event_end_date"><?php _e( 'Event End date:', 'event_meta_box' ); ?></label><br>
		<input type="text" name="event_end_date" id="event_end_date" value="<?php echo event_meta_box_get_meta( 'event_end_date' ); ?>">
	</p>	

<p>
		<label for="event_end_time"><?php _e( 'Event End time:', 'event_meta_box' ); ?></label><br>
		<input type="text" name="event_end_time" id="event_end_time" value="<?php echo event_meta_box_get_meta( 'event_end_time' ); ?>">
	</p>	

<h4 class="metabox-field-title">Who should your audience contact for more information?</h4>
<p>
			<label for="lccc_event_contact_name"><?php _e( 'Name:', 'event_meta_box' ); ?></label><br>
			<input class="widefat"  type="text" name="lccc_event_contact_name" id="lccc_event_contact_name" value="<?php echo event_meta_box_get_meta( 'lccc_event_contact_name' ); ?>">
		<label for="event_meta_box_contact_phone_"><?php _e( 'Phone:', 'event_meta_box' ); ?></label><br>
		<input class="widefat"  type="text" name="event_meta_box_contact_phone_" id="event_meta_box_contact_phone_" value="<?php echo event_meta_box_get_meta( 'event_meta_box_contact_phone_' ); ?>">
		<label for="event_meta_box_contact_email"><?php _e( 'Email:', 'event_meta_box' ); ?></label><br>
		<input class="widefat"  type="text" name="event_meta_box_contact_email" id="event_meta_box_contact_email" value="<?php echo event_meta_box_get_meta( 'event_meta_box_contact_email' ); ?>">

	<label for="event_meta_box_associated_web_address_"><?php _e( 'Website:', 'event_meta_box' ); ?></label><br>
		<input class="widefat"  type="text" name="event_meta_box_associated_web_address_" id="event_meta_box_associated_web_address_" value="<?php echo event_meta_box_get_meta( 'event_meta_box_associated_web_address_' ); ?>">
	</p>

<?php
}

function event_meta_box_save( $post_id ) {
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
	if ( ! isset( $_POST['event_meta_box_nonce'] ) || ! wp_verify_nonce( $_POST['event_meta_box_nonce'], '_event_meta_box_nonce' ) ) return;
	if ( ! current_user_can( 'edit_post', $post_id ) ) return;

	if ( isset( $_POST['event_meta_box_name'] ) )
		update_post_meta( $post_id, 'event_meta_box_name', esc_attr( $_POST['event_meta_box_name'] ) );
	if ( isset( $_POST['event_meta_box_phone'] ) )
		update_post_meta( $post_id, 'event_meta_box_phone', esc_attr( $_POST['event_meta_box_phone'] ) );
	if ( isset( $_POST['event_meta_box_e_mail'] ) )
		update_post_meta( $post_id, 'event_meta_box_e_mail', esc_attr( $_POST['event_meta_box_e_mail'] ) );
	
	
	if ( isset( $_POST['event_meta_box_employee'] ) )
		update_post_meta( $post_id, 'event_meta_box_employee', esc_attr( $_POST['event_meta_box_employee'] ) );
	else
		update_post_meta( $post_id, 'event_meta_box_employee', null );
	if ( isset( $_POST['event_meta_box_community'] ) )
		update_post_meta( $post_id, 'event_meta_box_community', esc_attr( $_POST['event_meta_box_community'] ) );
	else
		update_post_meta( $post_id, 'event_meta_box_community', null );
	
	if ( isset( $_POST['event_meta_box_students'] ) )
		update_post_meta( $post_id, 'event_meta_box_students', esc_attr( $_POST['event_meta_box_students'] ) );
	else
		update_post_meta( $post_id, 'event_meta_box_students', null );

	if ( isset( $_POST['event_meta_box_event_location'] ) )
		update_post_meta( $post_id, 'event_meta_box_event_location', esc_attr( $_POST['event_meta_box_event_location'] ) );
	
	if ( isset( $_POST['event_start_date'] ) )
   update_post_meta( $post_id, 'event_start_date', esc_attr( $_POST['event_start_date'] ) );
	
if ( isset( $_POST['event_start_time'] ) )
   update_post_meta( $post_id, 'event_start_time', esc_attr( $_POST['event_start_time'] ) ); 
	
	if ( isset( $_POST['event_end_date'] ) )
   update_post_meta( $post_id, 'event_end_date', esc_attr( $_POST['event_end_date'] ) ); 
	
	if ( isset( $_POST['event_end_time'] ) )
   update_post_meta( $post_id, 'event_end_time', esc_attr( $_POST['event_end_time'] ) ); 	

	if ( isset( $_POST['event_meta_box_event_end_date_and_time_'] ) )
		update_post_meta( $post_id, 'event_meta_box_event_end_date_and_time_', esc_attr( $_POST['event_meta_box_event_end_date_and_time_'] ) );	
	
	if ( isset( $_POST['event_meta_box_ticket_price_s_'] ) )
		update_post_meta( $post_id, 'event_meta_box_ticket_price_s_', esc_attr( $_POST['event_meta_box_ticket_price_s_'] ) );
	if ( isset( $_POST['event_meta_box_department_organization_sponsor_'] ) )
		update_post_meta( $post_id, 'event_meta_box_department_organization_sponsor_', esc_attr( $_POST['event_meta_box_department_organization_sponsor_'] ) );
	
	
	if ( isset( $_POST['lccc_event_contact_name'] ) )
		update_post_meta( $post_id, 'lccc_event_contact_name', esc_attr( $_POST['lccc_event_contact_name'] ) );	
		
	if ( isset( $_POST['event_meta_box_contact_phone_'] ) )
		update_post_meta( $post_id, 'event_meta_box_contact_phone_', esc_attr( $_POST['event_meta_box_contact_phone_'] ) );
	
	if ( isset( $_POST['event_meta_box_contact_email'] ) )
		update_post_meta( $post_id, 'event_meta_box_contact_email', esc_attr( $_POST['event_meta_box_contact_email'] ) );
	
	if ( isset( $_POST['event_meta_box_associated_web_address_'] ) )
		update_post_meta( $post_id, 'event_meta_box_associated_web_address_', esc_attr( $_POST['event_meta_box_associated_web_address_'] ) );
	
	if ( isset( $_POST['event_meta_box_display_start_date_and_time'] ) )
		update_post_meta( $post_id, 'event_meta_box_display_start_date_and_time', esc_attr( $_POST['event_meta_box_display_start_date_and_time'] ) );
	if ( isset( $_POST['event_meta_box_display_end_date_and_time'] ) )
		update_post_meta( $post_id, 'event_meta_box_display_end_date_and_time', esc_attr( $_POST['event_meta_box_display_end_date_and_time'] ) );
}
add_action( 'save_post', 'event_meta_box_save' );

function lorainccc_db_icons_box_get_meta( $value ) {
	global $post;

	$field = get_post_meta( $post->ID, $value, true );
	if ( ! empty( $field ) ) {
		return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
	} else {
		return false;
	}
}

function lorainccc_db_icons_box_add_meta_box() {
	add_meta_box(
		'lorainccc_db_icons_box-event-meta-box',
		__( 'Dashboard Icon Meta Box', 'lorainccc_db_icons_box' ),
		'lorainccc_db_icons_box_html',
		array('dashboard_icons'),
		'advanced',
		'core'
	);
}
add_action( 'add_meta_boxes', 'lorainccc_db_icons_box_add_meta_box' );


function lorainccc_db_icons_box_html( $post) {
	wp_nonce_field( '_lorainccc_db_icons_box_nonce', 'lorainccc_db_icons_box_nonce' ); ?>
	
<script>
jQuery(document).ready(function(){
jQuery('#event_start_date').datepicker({
	dateFormat: "yy-mm-dd"
});
jQuery('#event_start_time').timepicker({
	timeFormat: "hh:mm tt"
});
jQuery('#event_end_date').datepicker({
	dateFormat: "yy-mm-dd"
});
jQuery('#event_end_time').timepicker({
	timeFormat: "hh:mm tt"
});	

});
</script>

<h4>Associated Link:</h4>
	<p>
		<label for="lorainccc_db_icons_box_link"><?php _e( 'Associated Link', 'lorainccc_db_icons_box' ); ?></label><br>
		<input class="widefat" type="text" name="lorainccc_db_icons_box_link" id="lorainccc_db_icons_box_link" value="<?php echo lorainccc_db_icons_box_get_meta( 'lorainccc_db_icons_box_link' ); ?>">
	
	</p>	

<?php
}

function lorainccc_db_icons_box_save( $post_id ) {
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
	if ( ! isset( $_POST['lorainccc_db_icons_box_nonce'] ) || ! wp_verify_nonce( $_POST['lorainccc_db_icons_box_nonce'], '_lorainccc_db_icons_box_nonce' ) ) return;
	if ( ! current_user_can( 'edit_post', $post_id ) ) return;

	if ( isset( $_POST['lorainccc_db_icons_box_link'] ) )
		update_post_meta( $post_id, 'lorainccc_db_icons_box_link', esc_attr( $_POST['lorainccc_db_icons_box_link'] ) );

}
add_action( 'save_post', 'lorainccc_db_icons_box_save' );

function lorainccc_spotlight_box_get_meta( $value ) {
	global $post;

	$field = get_post_meta( $post->ID, $value, true );
	if ( ! empty( $field ) ) {
		return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
	} else {
		return false;
	}
}

function lorainccc_spotlight_box_add_meta_box() {
	add_meta_box(
		'lorainccc_spotlight_box-event-meta-box',
		__( 'Dashboard Icon Meta Box', 'lorainccc_spotlight_box' ),
		'lorainccc_spotlight_box_html',
		array('spotlights'),
		'advanced',
		'core'
	);
}
add_action( 'add_meta_boxes', 'lorainccc_spotlight_box_add_meta_box' );


function lorainccc_spotlight_box_html( $post) {
	wp_nonce_field( '_lorainccc_spotlight_box_nonce', 'lorainccc_spotlight_box_nonce' ); ?>
	
<script>
jQuery(document).ready(function(){
jQuery('#event_start_date').datepicker({
	dateFormat: "yy-mm-dd"
});
jQuery('#event_start_time').timepicker({
	timeFormat: "hh:mm tt"
});
jQuery('#event_end_date').datepicker({
	dateFormat: "yy-mm-dd"
});
jQuery('#event_end_time').timepicker({
	timeFormat: "hh:mm tt"
});	

});
</script>

	<p>
		<label for="lorainccc_spotlight_box_sub_header"><?php _e( 'Sub Header', 'lorainccc_spotlight_box' ); ?></label><br>
		<input class="widefat" type="text" name="lorainccc_spotlight_box_sub_header" id="lorainccc_spotlight_box_sub_header" value="<?php echo lorainccc_spotlight_box_get_meta( 'lorainccc_spotlight_box_sub_header' ); ?>">
	
	</p>	
	<p>
		<label for="lorainccc_spotlight_box_link"><?php _e( 'Associated Link', 'lorainccc_spotlight_box' ); ?></label><br>
		<input class="widefat" type="text" name="lorainccc_spotlight_box_link" id="lorainccc_spotlight_box_link" value="<?php echo lorainccc_spotlight_box_get_meta( 'lorainccc_spotlight_box_link' ); ?>">
	
	</p>	

<?php
}

function lorainccc_spotlight_box_save( $post_id ) {
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
	if ( ! isset( $_POST['lorainccc_spotlight_box_nonce'] ) || ! wp_verify_nonce( $_POST['lorainccc_spotlight_box_nonce'], '_lorainccc_spotlight_box_nonce' ) ) return;
	if ( ! current_user_can( 'edit_post', $post_id ) ) return;

	if ( isset( $_POST['lorainccc_spotlight_box_sub_header'] ) )
		update_post_meta( $post_id, 'lorainccc_spotlight_box_sub_header', esc_attr( $_POST['lorainccc_spotlight_box_sub_header'] ) );
	
		if ( isset( $_POST['lorainccc_spotlight_box_link'] ) )
		update_post_meta( $post_id, 'lorainccc_spotlight_box_link', esc_attr( $_POST['lorainccc_spotlight_box_link'] ) );

}
add_action( 'save_post', 'lorainccc_spotlight_box_save' );

function lorainccc_lccc_highlight_box_get_meta( $value ) {
	global $post;

	$field = get_post_meta( $post->ID, $value, true );
	if ( ! empty( $field ) ) {
		return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
	} else {
		return false;
	}
}

function lorainccc_lccc_highlight_box_add_meta_box() {
	add_meta_box(
		'lorainccc_lccc_highlight_box-event-meta-box',
		__( 'Dashboard Icon Meta Box', 'lorainccc_lccc_highlight_box' ),
		'lorainccc_lccc_highlight_box_html',
		array('highlight'),
		'advanced',
		'core'
	);
}
add_action( 'add_meta_boxes', 'lorainccc_lccc_highlight_box_add_meta_box' );


function lorainccc_lccc_highlight_box_html( $post) {
	wp_nonce_field( '_lorainccc_lccc_highlight_box_nonce', 'lorainccc_lccc_highlight_box_nonce' ); ?>
	
<script>
jQuery(document).ready(function(){
jQuery('#event_start_date').datepicker({
	dateFormat: "yy-mm-dd"
});
jQuery('#event_start_time').timepicker({
	timeFormat: "hh:mm tt"
});
jQuery('#event_end_date').datepicker({
	dateFormat: "yy-mm-dd"
});
jQuery('#event_end_time').timepicker({
	timeFormat: "hh:mm tt"
});	

});
</script>

	<p>
		<label for="lorainccc_lccc_highlight_box_bg_color"><?php _e( 'Background Color', 'lorainccc_lccc_highlight_box' ); ?></label><br>
		<input class="widefat" type="text" name="lorainccc_lccc_highlight_box_bg_color" id="lorainccc_lccc_highlight_box_bg_color" value="<?php echo lorainccc_lccc_highlight_box_get_meta( 'lorainccc_lccc_highlight_box_bg_color' ); ?>">
	</p>	
	<p>
		<label for="lorainccc_lccc_highlight_box_link"><?php _e( 'Associated Link', 'lorainccc_lccc_highlight_box' ); ?></label><br>
		<input class="widefat" type="text" name="lorainccc_lccc_highlight_box_link" id="lorainccc_lccc_highlight_box_link" value="<?php echo lorainccc_lccc_highlight_box_get_meta( 'lorainccc_lccc_highlight_box_link' ); ?>">
	
	</p>	

<?php
}

function lorainccc_lccc_highlight_box_save( $post_id ) {
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
	if ( ! isset( $_POST['lorainccc_lccc_highlight_box_nonce'] ) || ! wp_verify_nonce( $_POST['lorainccc_lccc_highlight_box_nonce'], '_lorainccc_lccc_highlight_box_nonce' ) ) return;
	if ( ! current_user_can( 'edit_post', $post_id ) ) return;

	if ( isset( $_POST['lorainccc_lccc_highlight_box_bg_color'] ) )
		update_post_meta( $post_id, 'lorainccc_lccc_highlight_box_bg_color', esc_attr( $_POST['lorainccc_lccc_highlight_box_bg_color'] ) );
	
		if ( isset( $_POST['lorainccc_lccc_highlight_box_link'] ) )
		update_post_meta( $post_id, 'lorainccc_lccc_highlight_box_link', esc_attr( $_POST['lorainccc_lccc_highlight_box_link'] ) );

}
add_action( 'save_post', 'lorainccc_lccc_highlight_box_save' );




?>